### ISSUE TITLE
Save `local_resinos` field in `.resin-sync.yml`

### ISSUE THREAD

**Issue by lekkas** [resin-io-playground/resin-toolbox#13]
`resin-sync.yml` will save the following options related to local ResinOS development:

``` yml
local_resinos:
  repository_name: ApplicationName
  dockerfile: Dockerfile_SHA256
  package_json: PackageJSON_SHA256
```
