### ISSUE TITLE
Add init command

### ISSUE THREAD

**Issue by lekkas** [resin-io-playground/resin-toolbox#14]
If no `.resin-sync.yml` is found in the source directory or no `local_resinos` field is found in it, prompt the user to run `resin-toolbox init`. This will:
- [x] Select a **repository name** for the application and save it into `local_resinos: repository_name` field
- [x] Save `local_resinos: dockerfile` field (`sha256`)
- [x] Save `local_resinos: package_json` field (`sha256`)
- [x] Initiate first docker build and tag the image as **latest**

A few more implementation notes:
- If `repository_name` already exists in the device, fail with an error and prompt user to choose another name
- If no `Dockerfile` is found in the root project directory, fail with an error. Local, on-device resinOS container builds do not currently support native `package.json` builds like resin.io builders do.

**Comment by shaunmulligan** [comment]
@lekkas the `local_resinos` key would indicate to `rdt` that we want to sync locally right, in the case of a resin.io device.

**Comment by lekkas** [comment]
@shaunmulligan `.resin-sync.yml` will be reused in the different sync cases (local/remote resin.io/resinos device sync), so simply checking the `local_resinos` key will not be enough. `rdt` should instead provide command line options/arguments to specify whether a `sync` (a.k.a `deploy`) will target  a local or a remote device.

The `local_resinos` field would be used to save settings related to the corresponding case (and the one we are targeting atm), so it will look like:

``` yml
uuid: abcdef123456
destination: /usr/src/app
port: 22
before: echo Start
after: echo Done
ignore: [ 'ignore_item1', 'ignore_item2' ]
local_resinos:
  port: 22222
  repository_name: node_server
  build_triggers: [ 'package.json', 'requirements.txt' ]
```

Does this make sense? ^
